### PR TITLE
📖 Add example - running in browser

### PR DESCRIPTION
**Pull request by chinanf-boy**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: example

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

---

## Just ` example`

1. cd `vue-promised/example`

2. `npm  i` / `yarn`

3. ` npm run dev `

>【dont forget the vue-promised/example/index.js, you add  // eslint-disable-next-line】-

you need `cd vue-promised/` and `npm  i `/ `yarn`

### CODE REVIEW

**Comment by posva** [comment]
Thanks a lot for the PR!
Were you missing a way to run the example? I was using poi to run the example but I think I should put a demo that can be accessed in the README.
I prefer not to add more dependencies to the package.json file

**Comment by chinanf-boy** [comment]
I see, is a lot of node_modules downloaded in` example`☠️

I just see your example - seem like where i run the demo ? that question

Is your can Add a demo link to README, Great!😊

**Comment by chinanf-boy** [comment]
Add thanks to share poi, i don't even know ` poi` before

and i try, help a lot of tool

**Comment by posva** [comment]
I added a demo btw! it's in the link at the top of the homepage

**Pull request closed without merging**
